import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "@/styles/global.scss";
import ModalRouter from "@/components/Modal/router";

const NotoSansKR = Noto_Sans_KR({
	weight: ["100", "200", "300", "400", "500", "600", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "급식 관리 서비스",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={NotoSansKR.className}>
                {children}
                <ModalRouter />
            </body>
		</html>
	);
}
